creation_rules:
  # Shared base secrets — all envs
  - path_regex: shared\.sops\.yaml$
    age: age1pu8asvupqcy5q9r9razgh804l3969pnuq6w233x0vd04uzdv29sqez6k3m

  # p4ulcristian dev profile
  - path_regex: p4ulcristian\.sops\.yaml$
    age: age1pu8asvupqcy5q9r9razgh804l3969pnuq6w233x0vd04uzdv29sqez6k3m

  # Production
  - path_regex: prod\.sops\.yaml$
    age: age1pu8asvupqcy5q9r9razgh804l3969pnuq6w233x0vd04uzdv29sqez6k3m
